### ISSUE TITLE
[#1] Unexpected token 'export' in next@14.0.0

### ISSUE THREAD

**Issue by talha4real** [mirzayevkamal/next-snapchat-pixel#1]
To replicate the issue, just install the package in nextjs and call the init function.

`SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1280:20)
    at Module._compile (node:internal/modules/cjs/loader:1332:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/Users/talhabutt/Workspace/Dropin-site/dropin-site/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:179:18)
    at next-snapchat-pixel (/Users/talhabutt/Workspace/Dropin-site/dropin-site/.next/server/pages/index.js:1275:18)
    at __webpack_require__ (/Users/talhabutt/Workspace/Dropin-site/dropin-site/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/index.tsx:34:78)
    at __webpack_require__.a (/Users/talhabutt/Workspace/Dropin-site/dropin-site/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/pages/index.tsx:1:21)
    at ./src/pages/index.tsx (/Users/talhabutt/Workspace/Dropin-site/dropin-site/.next/server/pages/index.js:1243:1) {
  page: '/'
}`

**Comment by talha4real** [comment]
This pr fixes this

https://github.com/mirzayevkamal/next-snapchat-pixel/pull/2

**Comment by mirzayevkamal** [comment]
@talha4real use dynamic import with `{ssr:false}`

**Comment by talha4real** [comment]
i see my mistake, thanks man
